[[themes]]
name = "tokyo-night"

[themes.palette]
background    = "#1a1b26"
foreground    = "#c0caf5"
black         = "#15161e"
blue          = "#7aa2f7"
cyan          = "#7dcfff"
green         = "#9ece6a"
magenta       = "#bb9af7"
red           = "#f7768e"
white         = "#a9b1d6"
yellow        = "#e0af68"
bright_black  = "#414868"
bright_blue   = "#7aa2f7"
bright_cyan   = "#7dcfff"
bright_green  = "#9ece6a"
bright_magenta = "#bb9af7"
bright_red    = "#f7768e"
bright_white  = "#c0caf5"
bright_yellow = "#e0af68"

[themes.component_style]
block_title                    = { fg = "Blue",        modifiers = ["Bold"] }
border                         = { fg = "BrightBlack" }
playback_status                = { fg = "Green",       modifiers = ["Bold"] }
playback_track                 = { fg = "Cyan",        modifiers = ["Bold"] }
playback_artists               = { fg = "Blue" }
playback_album                 = { fg = "Magenta" }
playback_genres                = { fg = "BrightBlack", modifiers = ["Italic"] }
playback_metadata              = { fg = "BrightBlack" }
playback_progress_bar          = { fg = "Blue",        bg = "BrightBlack" }
playback_progress_bar_unfilled = { bg = "BrightBlack" }
current_playing                = { fg = "Green",       modifiers = ["Bold"] }
page_desc                      = { fg = "Cyan",        modifiers = ["Bold"] }
playlist_desc                  = { fg = "BrightBlack", modifiers = ["Dim"] }
table_header                   = { fg = "Blue" }
selection                      = { fg = "Cyan",        modifiers = ["Reversed", "Bold"] }
like                           = { fg = "Red" }
lyrics_played                  = { modifiers = ["Dim"] }
lyrics_playing                 = { fg = "Green",       modifiers = ["Bold"] }
