format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$line_break$character"""

palette = "tokyo_night"

[palettes.tokyo_night]
slate = "#414868"
bright = "#c0caf5"
blue = "#7aa2f7"
white = "#e3e5e5"
storm = "#394260"
night = "#212736"
abyss = "#1d2230"
grey = "#a0a9cb"
sky = "#7aa2f7"
red = "#f7768e"

[os]
disabled = false
style = "fg:bright"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "fg:bright"
style_root = "fg:red"
format = '[$user]($style) '

[directory]
style = "fg:blue bold"
format = 'in [$path]($style) '
truncation_length = 2
truncation_symbol = "../"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Development" = "󰲋 "

[git_branch]
symbol = " "
style = "fg:sky"
format = 'on [$symbol$branch]($style) '
truncation_length = 20
truncation_symbol = "…"

[git_status]
style = "fg:red"
format = '[$all_status$ahead_behind]($style) '

[nodejs]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[c]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[rust]
symbol = "󱘗 "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[golang]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[php]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[java]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[kotlin]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[haskell]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[python]
symbol = " "
style = "fg:sky"
format = 'via [$symbol($version)]($style) '

[docker_context]
symbol = " "
style = "fg:sky"
format = 'via [$symbol$context]($style) '

[time]
disabled = false
time_format = "%R"
style = "fg:grey"
format = 'at [$time]($style) '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❯](bold blue)'
vimcmd_replace_one_symbol = '[❯](bold sky)'
vimcmd_replace_symbol = '[❯](bold sky)'
vimcmd_visual_symbol = '[❯](bold blue)'
