format = """
$os\
$username\
[](bg:blue fg:slate)\
$directory\
[](fg:blue bg:storm)\
$git_branch\
$git_status\
[](fg:storm bg:night)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:night bg:night)\
$docker_context\
[](fg:night bg:abyss)\
$time\
[ ](fg:abyss)\
$line_break$character"""

palette = "tokyo_night"

[palettes.tokyo_night]
slate = "#414868"
bright = "#c0caf5"
blue = "#769ff0"
white = "#e3e5e5"
storm = "#394260"
night = "#212736"
abyss = "#1d2230"
grey = "#a0a9cb"
sky = "#769ff0"
red = "#ff757f"

[os]
disabled = false
style = "bg:slate fg:bright"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:slate fg:bright"
style_root = "bg:slate fg:bright"
format = '[ $user ]($style)'

[directory]
style = "fg:white bg:blue"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Development" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:night"
format = '[[ $symbol $branch ](fg:sky bg:storm)]($style)'
truncation_length = 20
truncation_symbol = "…"

[git_status]
style = "bg:night"
format = '[[($all_status$ahead_behind )](fg:sky bg:storm)]($style)'

[nodejs]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[c]
symbol = " "
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[rust]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[golang]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[php]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[java]
symbol = " "
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[kotlin]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[haskell]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[python]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $version) ](fg:sky bg:night)]($style)'

[docker_context]
symbol = ""
style = "bg:night"
format = '[[ $symbol( $context) ](fg:sky bg:night)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:blue"
format = '[[  $time ](fg:grey bg:abyss)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❯](bold blue)'
vimcmd_replace_one_symbol = '[❯](bold sky)'
vimcmd_replace_symbol = '[❯](bold sky)'
vimcmd_visual_symbol = '[❯](bold blue)'
